# Libraries

In [2]:
import os
import pandas as pd
from datetime import datetime
pd.io.formats.excel.ExcelFormatter.header_style = None
pd.options.display.float_format = '{:,.2f}'.format

# Parameters

In [3]:
today = datetime.today()
year = today.year
week = today.isocalendar()[1]

# Import Data

In [13]:
path = r'\\NASPRO.infovisiontv.com\DWH01\Cognos\Genomma lab USA\US Data\VIP Suerox\{0}\W {1} {0}'
path = path.format(year, str(week).zfill(2))
filename = '{0}_{1}_VIP.xlsx'
filename = filename.format(year, str(week).zfill(2))

In [14]:
files = [f for f in os.listdir(path) if f != filename]

In [18]:
files

['Suerox PR VTM Sell-out Wk 7 2-14-22 without CVS WAGs and WMT.xlsx',
 'Suerox SO Week 7 for USA and PR (breakdown) 2-14-22.xlsx',
 'Weekly SO - by detail.csv']

In [24]:
df_pr = pd.read_excel(
    path + '\\Suerox PR VTM Sell-out Wk 7 2-14-22 without CVS WAGs and WMT.xlsx', 
    header= 3
)

In [28]:
df_pr

,Week,Distributor,Retail Accounts,Address,City,State,Zip Code,Unnamed: 7,UPC,Product Description,Cases,Units,Dollars
0,7.00,Vaqueria Tres Monjitas,Tres Monjitas,"215 Federico Costa, Urb. Ind. Tres Monjitas",Hato Rey,PR,918.00,NaN,"650,066,003,226.00",SUEROX BLUEBERRY REBOOT 21.3 OZ,238.17,2858,"4,001.20"
1,7.00,Vaqueria Tres Monjitas,Tres Monjitas,"215 Federico Costa, Urb. Ind. Tres Monjitas",Hato Rey,PR,918.00,NaN,"650,066,003,288.00",SUEROX GRAPE BOOST 21.3 OZ,236.83,2842,"3,978.80"
2,7.00,Vaqueria Tres Monjitas,Tres Monjitas,"215 Federico Costa, Urb. Ind. Tres Monjitas",Hato Rey,PR,918.00,NaN,"650,066,003,264.00",SUEROX ORANGE RESCUE 21.3 OZ,184.75,2217,"3,103.80"
3,7.00,Vaqueria Tres Monjitas,Tres Monjitas,"215 Federico Costa, Urb. Ind. Tres Monjitas",Hato Rey,PR,918.00,NaN,"650,066,003,240.00",SUEROX STRAWBERRY/KIWI PUNCH 21.3 OZ,251.00,3012,"4,216.80"
4,7.00,Vaqueria Tres Monjitas,Tres Monjitas,"215 Federico Costa, Urb. Ind. Tres Monjitas",Hato Rey,PR,918.00,NaN,"650,240,058,684.00",SUEROX COCONUT REFRESH 21.3 OZ,155.25,1863,"2,608.20"
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grand Total,"1,066.00",12792,"17,908.80"

In [27]:
df_pr.dropna(axis=)

                    Product Description    Cases  Units   Dollars
0       SUEROX BLUEBERRY REBOOT 21.3 OZ   238.17   2858  4,001.20
1            SUEROX GRAPE BOOST 21.3 OZ   236.83   2842  3,978.80
2          SUEROX ORANGE RESCUE 21.3 OZ   184.75   2217  3,103.80
3  SUEROX STRAWBERRY/KIWI PUNCH 21.3 OZ   251.00   3012  4,216.80
4        SUEROX COCONUT REFRESH 21.3 OZ   155.25   1863  2,608.20
5                           Grand Total 1,066.00  12792 17,908.80

In [16]:
df = pd.DataFrame()
for file in files:
    try:
        aux = pd.read_excel(path + '\\' + file)
    except:
        aux = pd.read_csv(path + '\\' + file)
    df = pd.concat([df, aux])

In [17]:
df

,Puerto Rico Suerox Sell-out Week 7 2022,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 0,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,No Filters Selected,Calculated Column,Calculated Column.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Week,Distributor,Retail Accounts,Address,City,State,Zip Code,NaN,UPC,Product Description,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,Vaqueria Tres Monjitas,Tres Monjitas,"215 Federico Costa, Urb. Ind. Tres Monjitas",Hato Rey,PR,00918,NaN,650066003226,SUEROX BLUEBERRY REBOOT 21.3 OZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,Vaqueria Tres Monjitas,Tres Monjitas,"215 Federico Costa, Urb. Ind. Tres Monjitas",Hato Rey,PR,00918,NaN,650066003288,SUEROX GRAPE BOOST 21.3 OZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737,NaN,ST JOSEPH FOOD MART,1817 N SAINT JOSEPH ST,GONZALES,TX,78629,NaN,3265418,SueroX Grape 21oz/12ct,"=""650066003288""",...,"L & F Distributors - Beeville, TX",NaN,NaN,NaN,NaN,NaN,NaN,1,12,16.8
1738,NaN,ST JOSEPH FOOD MART,1817 N SAINT JOSEPH ST,GONZALES,TX,78629,NaN,3265418,SueroX Blueberry 21oz/12ct,"=""650066003226""",...,"L & F Distributors - Beeville, TX",NaN,NaN,NaN,NaN,NaN,NaN,1,12,16.8
1739,NaN,MD MINI MARKET,6658 BOULDER HWY,LAS VEGAS,NV,89122,NaN,2882224,SueroX Strawberry Kiwi 21oz/12ct,"=""650066003240""",...,"Nevada Beverage - Tropicana, NV",NaN,NaN,NaN,NaN,NaN,NaN,1,12,16.8
1740,NaN,MD MINI MARKET,6658 BOULDER HWY,LAS VEGAS,NV,89122,NaN,2882224,SueroX Orange 21oz/12ct,"=""650066003264""",...,"Nevada Beverage - Tropicana, NV",NaN,NaN,NaN,NaN,NaN,NaN,1,12,16.8
1741,NaN,SNAPPY FOODS,2607 N HIGHWAY 35,ARANSAS PASS,TX,78336,NaN,2399448,SueroX Blueberry 21oz/12ct,"=""650066003226""",...,"L & F Distributors - Corpus Christi, TX",NaN,NaN,NaN,NaN,NaN,NaN,2,24,33.6